// @ts-nocheck
import { createCipheriv, createDecipheriv, createHash, randomBytes, randomUUID } from "node:crypto";
import { isIP } from "node:net";
import { lookup } from "node:dns/promises";
import { ComputeBudgetProgram, Connection, PublicKey, TransactionInstruction, TransactionMessage, VersionedTransaction } from "@solana/web3.js";
import { createTransferCheckedInstruction, getAssociatedTokenAddressSync } from "@solana/spl-token";
import { X402DiscoverResponseSchema, X402PaymentRequirementsSchema, X402PreparedPaymentSchema, X402ReceiptSchema, X402ResourceSchema, X402_MARKET_PROVIDER_CATALOG, X402_SOLANA_MAINNET, X402_SOLANA_USDC_MINT, type X402DiscoverResponse, type X402PreparedPayment, type X402Receipt, type X402Resource } from "@mirae/contracts";
import type { RuntimeDatabase } from "../storage/database.js";
import type { LocalEncryptedKeystore } from "../storage/keystore.js";
import type { WalletOnboardingService } from "../wallet/onboarding.js";

const MEMO_PROGRAM = new PublicKey("MemoSq4gqABAXKb96qnH8TysNcWxMyWCqXgDLGmfcHr");
const AAD = Buffer.from("mirae-x402-receipts-v1", "utf8");
const MAX_PROVIDER_DOWNLOAD_BYTES = 1_000_000;
const MAX_STORED_EVIDENCE_BYTES = 63_000;
type PreparedRecord = X402PreparedPayment & { input: unknown };

export class X402DesktopService {
  readonly #prepared = new Map<string, PreparedRecord>();
  constructor(readonly database: RuntimeDatabase, readonly secrets: LocalEncryptedKeystore, readonly wallets: WalletOnboardingService) {}

  async discover(query: string, maxAtomic: bigint, limit: number): Promise<Pick<X402DiscoverResponse, "resources" | "rejectedCount">> {
    void query;
    const resources: X402Resource[] = []; let rejectedCount = 0;
    const results = await Promise.allSettled(X402_MARKET_PROVIDER_CATALOG.slice(0, limit).map(async (candidate) => {
      await safeUrl(candidate.url); const response = await fetch(candidate.url, { method: candidate.method, headers: { Accept: "application/json" }, redirect: "error", signal: AbortSignal.timeout(15_000) }); if (response.status !== 402) throw new Error(`Provider did not return x402 requirements (${response.status})`); const encoded = response.headers.get("payment-required") ?? response.headers.get("x-payment-required"); const challenge = encoded ? JSON.parse(Buffer.from(encoded, "base64").toString("utf8")) : JSON.parse(await limitedText(response, 32_000)); if (challenge.x402Version !== 2 || !Array.isArray(challenge.accepts)) throw new Error("Provider returned invalid x402 requirements"); const requirements = X402PaymentRequirementsSchema.parse(challenge.accepts.find((entry: any) => entry?.scheme === "exact" && entry?.network === X402_SOLANA_MAINNET && entry?.asset === X402_SOLANA_USDC_MINT)); if (requirements.resource && requirements.resource !== candidate.url) throw new Error("Provider requirements target another resource"); if (BigInt(requirements.amount) > maxAtomic) throw new Error("price exceeds limit"); const rpc = (await this.secrets.getSecret("solana-rpc-url")) ?? "https://api.mainnet-beta.solana.com"; const connection = new Connection(rpc, "confirmed"); const [sponsorBalance, destination] = await Promise.all([connection.getBalance(new PublicKey(requirements.extra.feePayer), "confirmed"), connection.getAccountInfo(getAssociatedTokenAddressSync(new PublicKey(X402_SOLANA_USDC_MINT), new PublicKey(requirements.payTo)), "confirmed")]); if (sponsorBalance < 1_000_000 || !destination) throw new Error("Provider sponsored payment rail is unavailable"); return X402ResourceSchema.parse({ id: hash({ url: candidate.url, method: candidate.method, requirements }), resource: { url: candidate.url, description: candidate.description, mimeType: "application/json", serviceName: candidate.serviceName, tags: [...candidate.tags] }, method: candidate.method, requirements, quality: { callsLast30Days: null, uniquePayersLast30Days: null, lastCalledAt: null }, discoveredAt: new Date().toISOString() });
    }));
    for (const result of results) { if (result.status === "fulfilled") resources.push(result.value); else rejectedCount += 1; }
    return X402DiscoverResponseSchema.pick({ resources: true, rejectedCount: true }).parse({ resources, rejectedCount });
  }

  async prepare(input: { sessionId: string; walletAddress: string; resource: X402Resource; requestInput: unknown; maxResourceAtomic: bigint; maxMissionAtomic: bigint }): Promise<X402PreparedPayment> {
    if (input.maxResourceAtomic > 100_000n || input.maxMissionAtomic > 1_000_000n || input.maxResourceAtomic > input.maxMissionAtomic) throw new Error("x402 budget exceeds hard cap");
    const spent = (await this.listReceipts()).filter((item) => item.sessionId === input.sessionId && ["SUBMITTED", "SETTLED", "RESOURCE_RECEIVED"].includes(item.status)).reduce((sum, item) => sum + BigInt(item.amount), 0n);
    const live = await liveRequirements(input.resource, input.requestInput); if (hash(live) !== hash(input.resource.requirements)) throw new Error("Provider requirements changed; discover again"); const amount = BigInt(live.amount); if (amount > input.maxResourceAtomic || spent + amount > input.maxMissionAtomic) throw new Error("x402 purchase exceeds approved budget");
    const rpc = (await this.secrets.getSecret("solana-rpc-url")) ?? "https://api.mainnet-beta.solana.com"; const connection = new Connection(rpc, "confirmed"); const payer = new PublicKey(input.walletAddress); const mint = new PublicKey(X402_SOLANA_USDC_MINT); const source = getAssociatedTokenAddressSync(mint, payer); const destination = getAssociatedTokenAddressSync(mint, new PublicKey(live.payTo));
    const [sourceInfo, destinationInfo, balance] = await Promise.all([connection.getAccountInfo(source), connection.getAccountInfo(destination), connection.getTokenAccountBalance(source).catch(() => null)]); if (!sourceInfo || !balance || BigInt(balance.value.amount) < amount) throw new Error("USDC balance is insufficient for this x402 payment"); if (!destinationInfo) throw new Error("Provider USDC recipient account does not exist");
    const latest = live.extra.recentBlockhash && live.extra.lastValidBlockHeight ? { blockhash: live.extra.recentBlockhash, lastValidBlockHeight: Number(live.extra.lastValidBlockHeight) } : await connection.getLatestBlockhash("confirmed"); const transaction = new VersionedTransaction(new TransactionMessage({ payerKey: new PublicKey(live.extra.feePayer), recentBlockhash: latest.blockhash, instructions: [ComputeBudgetProgram.setComputeUnitLimit({ units: 20_000 }), ComputeBudgetProgram.setComputeUnitPrice({ microLamports: 1_000 }), createTransferCheckedInstruction(source, mint, destination, payer, amount, 6), new TransactionInstruction({ programId: MEMO_PROGRAM, keys: [], data: Buffer.from(live.extra.memo ?? randomUUID().replaceAll("-", ""), "utf8") })] }).compileToV0Message());
    const [fee, simulation] = await Promise.all([connection.getFeeForMessage(transaction.message, "confirmed"), connection.simulateTransaction(transaction, { replaceRecentBlockhash: true, sigVerify: false })]); if (simulation.value.err) throw new Error(`x402 payment simulation failed: ${JSON.stringify(simulation.value.err)}`); const now = new Date(); const request = { method: input.resource.method, url: input.resource.resource.url, body: input.resource.method === "POST" ? input.requestInput ?? {} : null } as const; const prepared = X402PreparedPaymentSchema.parse({ id: randomUUID(), sessionId: input.sessionId, walletAddress: input.walletAddress, resource: { ...input.resource, requirements: live }, request, requestDigest: hash(request), requirementsDigest: hash(live), idempotencyKey: hash({ request, live, wallet: input.walletAddress, nonce: randomUUID() }), status: "AWAITING_SIGNATURE", expiresAt: new Date(now.getTime() + live.maxTimeoutSeconds * 1_000).toISOString(), createdAt: now.toISOString(), transactionBase64: Buffer.from(transaction.serialize()).toString("base64"), blockhash: latest.blockhash, lastValidBlockHeight: String(latest.lastValidBlockHeight), estimatedNetworkFeeLamports: String(fee.value ?? 0) }); this.#prepared.set(prepared.id, { ...prepared, input: input.requestInput }); return prepared;
  }

  async execute(input: { planId: string; sessionId: string; walletAddress: string }): Promise<X402Receipt> {
    const prepared = this.#prepared.get(input.planId); if (!prepared || prepared.sessionId !== input.sessionId || prepared.walletAddress !== input.walletAddress) throw new Error("Prepared x402 payment is unavailable for this session"); if (Date.parse(prepared.expiresAt) <= Date.now()) { this.#prepared.delete(input.planId); throw new Error("Prepared x402 payment expired"); }
    const transaction = VersionedTransaction.deserialize(Buffer.from(prepared.transactionBase64, "base64")); await this.wallets.withWalletWeb3Keypair(input.walletAddress, async (keypair) => { transaction.sign([keypair]); }); const signed = Buffer.from(transaction.serialize()).toString("base64"); const payload = { x402Version: 2, resource: prepared.resource.resource, accepted: prepared.resource.requirements, payload: { transaction: signed }, extensions: {} }; let receipt = baseReceipt(prepared, "SUBMITTED"); await this.save(receipt);
    try { let response: Response; try { response = await fetch(prepared.request.url, { method: prepared.request.method, headers: { Accept: "application/json", "PAYMENT-SIGNATURE": Buffer.from(JSON.stringify(payload)).toString("base64"), ...(prepared.request.method === "POST" ? { "Content-Type": "application/json" } : {}) }, body: prepared.request.method === "POST" ? JSON.stringify(prepared.request.body ?? {}) : undefined, redirect: "error", signal: AbortSignal.timeout(75_000) }); } catch (cause) { if (isTimeout(cause)) throw new Error("Provider retrieval timed out after signed proof submission; settlement is unknown. Check activity before retrying"); throw cause; } const encoded = response.headers.get("payment-response"); if (!response.ok || !encoded) throw new Error(`Provider did not settle x402 payment (${response.status})`); const settlement = JSON.parse(Buffer.from(encoded, "base64").toString("utf8")) as any; if (settlement.success !== true || settlement.network !== X402_SOLANA_MAINNET || typeof settlement.transaction !== "string") throw new Error("Provider settlement response is invalid"); const rawBody = await limitedText(response, MAX_PROVIDER_DOWNLOAD_BYTES); const body = compactEvidence(rawBody, prepared.input, MAX_STORED_EVIDENCE_BYTES); receipt = X402ReceiptSchema.parse({ ...receipt, status: "RESOURCE_RECEIVED", signature: settlement.transaction, settlement: { success: true, transaction: settlement.transaction, network: X402_SOLANA_MAINNET, ...(typeof settlement.payer === "string" ? { payer: settlement.payer } : {}) }, resourceResponse: { mimeType: response.headers.get("content-type")?.slice(0, 128) ?? "application/octet-stream", body, receivedAt: new Date().toISOString() }, updatedAt: new Date().toISOString() }); await this.save(receipt); this.#prepared.delete(input.planId); return receipt; } catch (error) { receipt = X402ReceiptSchema.parse({ ...receipt, status: "UNKNOWN", errorCode: "RESOURCE_FAILED", errorMessage: error instanceof Error ? error.message.slice(0, 500) : "Unknown provider outcome", updatedAt: new Date().toISOString() }); await this.save(receipt); throw error; }
  }

  async listReceipts(): Promise<X402Receipt[]> { const key = await this.key(); return this.database.listX402ReceiptRecords().map((row) => { const decipher = createDecipheriv("aes-256-gcm", key, Buffer.from(row.nonce, "base64")); decipher.setAAD(AAD); decipher.setAuthTag(Buffer.from(row.tag, "base64")); return X402ReceiptSchema.parse(JSON.parse(Buffer.concat([decipher.update(Buffer.from(row.ciphertext, "base64")), decipher.final()]).toString("utf8"))); }); }
  clearPrepared(): void { this.#prepared.clear(); }
  private async save(receipt: X402Receipt): Promise<void> { const key = await this.key(); const nonce = randomBytes(12); const cipher = createCipheriv("aes-256-gcm", key, nonce); cipher.setAAD(AAD); const ciphertext = Buffer.concat([cipher.update(JSON.stringify(receipt), "utf8"), cipher.final()]); this.database.upsertX402ReceiptRecord({ id: receipt.id, ciphertext: ciphertext.toString("base64"), nonce: nonce.toString("base64"), tag: cipher.getAuthTag().toString("base64"), updatedAt: receipt.updatedAt }); }
  private async key(): Promise<Buffer> { let encoded = await this.secrets.getSecret("x402-receipt-store-key"); if (!encoded) { encoded = randomBytes(32).toString("base64"); await this.secrets.setSecret("x402-receipt-store-key", encoded); } const key = Buffer.from(encoded, "base64"); if (key.length !== 32) throw new Error("x402 receipt key is invalid"); return key; }
}

async function liveRequirements(resource: X402Resource, input: unknown) { await safeUrl(resource.resource.url); const response = await fetch(resource.resource.url, { method: resource.method, headers: { Accept: "application/json", ...(resource.method === "POST" ? { "Content-Type": "application/json" } : {}) }, body: resource.method === "POST" ? JSON.stringify(input ?? {}) : undefined, redirect: "error", signal: AbortSignal.timeout(20_000) }); if (response.status !== 402) throw new Error(`Provider did not return x402 requirements (${response.status})`); const encoded = response.headers.get("payment-required") ?? response.headers.get("x-payment-required"); const value = encoded ? JSON.parse(Buffer.from(encoded, "base64").toString("utf8")) : JSON.parse(await limitedText(response, 32_000)); if (value.x402Version !== 2 || value.resource?.url !== resource.resource.url || !Array.isArray(value.accepts)) throw new Error("Provider returned invalid x402 requirements"); const requirements = X402PaymentRequirementsSchema.parse(value.accepts.find((entry: any) => entry?.scheme === "exact" && entry?.network === X402_SOLANA_MAINNET && entry?.asset === X402_SOLANA_USDC_MINT)); if (requirements.resource && requirements.resource !== resource.resource.url) throw new Error("Provider requirements target another resource"); return requirements; }
function baseReceipt(prepared: X402PreparedPayment, status: X402Receipt["status"]): X402Receipt { const now = new Date().toISOString(); return X402ReceiptSchema.parse({ id: randomUUID(), planId: prepared.id, sessionId: prepared.sessionId, walletAddress: prepared.walletAddress, resourceId: prepared.resource.id, resourceUrl: prepared.resource.resource.url, providerOrigin: new URL(prepared.resource.resource.url).origin, requestDigest: prepared.requestDigest, requirementsDigest: prepared.requirementsDigest, idempotencyKey: prepared.idempotencyKey, amount: prepared.resource.requirements.amount, asset: X402_SOLANA_USDC_MINT, payTo: prepared.resource.requirements.payTo, signature: null, status, settlement: null, resourceResponse: null, errorCode: null, errorMessage: null, createdAt: now, updatedAt: now }); }
function stable(value: unknown): string { if (value === null || typeof value !== "object") return JSON.stringify(value); if (Array.isArray(value)) return `[${value.map(stable).join(",")}]`; return `{${Object.entries(value as Record<string, unknown>).sort(([a], [b]) => a.localeCompare(b)).map(([key, entry]) => `${JSON.stringify(key)}:${stable(entry)}`).join(",")}}`; }
function hash(value: unknown): `sha256:${string}` { return `sha256:${createHash("sha256").update(stable(value)).digest("hex")}`; }
async function safeUrl(raw: string): Promise<void> { const url = new URL(raw); if (url.protocol !== "https:" || url.username || url.password || url.port || url.hostname === "localhost") throw new Error("Unsafe provider URL"); const addresses = isIP(url.hostname) ? [{ address: url.hostname }] : await lookup(url.hostname, { all: true }); if (addresses.some(({ address }) => isPrivateAddress(address))) throw new Error("Private provider URL is blocked"); }
export function isPrivateAddress(address: string): boolean { const normalized = address.toLowerCase(); if (normalized === "::1" || normalized === "0:0:0:0:0:0:0:1" || normalized.startsWith("fc") || normalized.startsWith("fd") || normalized.startsWith("fe8") || normalized.startsWith("fe9") || normalized.startsWith("fea") || normalized.startsWith("feb")) return true; const match = /^(\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})$/.exec(normalized); if (!match) return false; const octets = match.slice(1).map(Number); return octets[0] === 0 || octets[0] === 10 || octets[0] === 127 || (octets[0] === 169 && octets[1] === 254) || (octets[0] === 172 && octets[1] >= 16 && octets[1] <= 31) || (octets[0] === 192 && octets[1] === 168) || octets[0] >= 224; }
async function limitedText(response: Response, maximum: number): Promise<string> { const length = Number(response.headers.get("content-length") ?? 0); if (length > maximum) throw new Error("Provider response is too large"); const text = await response.text(); if (Buffer.byteLength(text) > maximum) throw new Error("Provider response is too large"); return text; }
function compactEvidence(rawBody: string, requestInput: unknown, maximum: number): string { const query = requestInput && typeof requestInput === "object" && typeof requestInput.query === "string" ? requestInput.query : ""; const symbols = [...new Set(query.toUpperCase().match(/\b(?:SOL|ETH|BTC|JUP|ONDO|DOGE|USDC)\b/g) ?? [])]; let evidence = rawBody; if (symbols.length) { try { const matches: unknown[] = []; collectEvidence(JSON.parse(rawBody), symbols, matches, 200); if (matches.length) evidence = JSON.stringify({ filteredFor: symbols, sourcePayloadBytes: Buffer.byteLength(rawBody), matches }); } catch {} } if (Buffer.byteLength(evidence) <= maximum) return evidence; const marker = "\n...[Mirae truncated oversized untrusted provider output]"; let result = Buffer.from(evidence).subarray(0, Math.max(0, maximum - Buffer.byteLength(marker))).toString("utf8"); while (Buffer.byteLength(result + marker) > maximum) result = result.slice(0, -1); return result + marker; }
function collectEvidence(value: unknown, symbols: string[], matches: unknown[], limit: number): void { if (matches.length >= limit || !value || typeof value !== "object") return; if (Array.isArray(value)) { for (const item of value) { if (matches.length >= limit) break; let preview = ""; try { preview = JSON.stringify(item).slice(0, 8_000).toUpperCase(); } catch {} if (symbols.some((symbol) => preview.includes(symbol))) matches.push(item); else collectEvidence(item, symbols, matches, limit); } return; } for (const [key, child] of Object.entries(value as Record<string, unknown>)) { if (matches.length >= limit) break; const upper = key.toUpperCase(); if (symbols.some((symbol) => upper === symbol || upper.includes(`${symbol}-`) || upper.includes(`${symbol}_`))) matches.push({ [key]: child }); else collectEvidence(child, symbols, matches, limit); } }
function isTimeout(value: unknown): boolean { return value instanceof Error && (value.name === "TimeoutError" || value.name === "AbortError" || /timeout|aborted/iu.test(value.message)); }
function record(value: unknown): value is Record<string, unknown> { return typeof value === "object" && value !== null && !Array.isArray(value); } function integer(value: unknown): number | null { return Number.isInteger(value) && Number(value) >= 0 ? Number(value) : null; } function date(value: unknown): string | null { return typeof value === "string" && Number.isFinite(Date.parse(value)) ? new Date(value).toISOString() : null; }
